import { ModuleMap } from 'jest-haste-map';

const roster = {
  pistons: [
    {
      name: 'Jordan Bone',
      position: 'Guard',
      number: '18',
      height: `6'9"`,
      weight: '209',
      age: 18,
      from: '',
      debut: '',
      years: 0,
      stats: {
        mpg: '0',
        fg: '0',
        three: '0',
        ft: '0',
        ppg: '0',
        rpg: '0',
        apg: '0',
        bpg: '0',
      },
    },
    {
      name: 'Bruce Brown',
      position: 'Guard',
      number: '6',
      height: `6'5"`,
      weight: '202',
      age: 23,
      from: 'University of Miami',
      debut: '2018',
      years: 1,
      stats: {
        mpg: '18.6',
        fg: '39.8',
        three: '25.8',
        ft: '75',
        ppg: '4.3',
        rpg: '2.5',
        apg: '1.2',
        bpg: '0.5',
      },
    },
    {
      name: 'Sekou Doumbouya',
      position: 'Forward',
      number: '45',
      height: `6'9"`,
      weight: '209',
      age: 18,
      from: '',
      debut: '',
      years: 0,
      stats: {
        mpg: '0',
        fg: '0',
        three: '0',
        ft: '0',
        ppg: '0',
        rpg: '0',
        apg: '0',
        bpg: '0',
      },
    },
    {
      name: 'Andre Drummond',
      position: 'Center',
      number: '0',
      height: `6'11"`,
      weight: '279',
      age: 26,
      from: 'Connecticut',
      debut: '2012',
      years: 7,
      stats: {
        mpg: '30.8',
        fg: '54.3',
        three: '14.7',
        ft: '44.8',
        ppg: '14.1',
        rpg: '13.7',
        apg: '1.2',
        bpg: '1.6',
      },
    },
    {
      name: 'Tim Frazier',
      position: 'Guard',
      number: '12',
      height: `6'1"`,
      weight: '170',
      age: 28,
      from: 'Penn State',
      debut: '2014',
      years: 5,
      stats: {
        mpg: '18,2',
        fg: '41.2',
        three: '32.9',
        ft: '73.1',
        ppg: '5.2',
        rpg: '2.4',
        apg: '4.1',
        bpg: '0.1',
      },
    },
    {
      name: 'Langston Galloway',
      position: 'Guard',
      number: '9',
      height: `6'2"`,
      weight: '200',
      age: 27,
      from: 'St. Joseph, PA',
      debut: '2014',
      years: 5,
      stats: {
        mpg: '22.4',
        fg: '38.7',
        three: '35.9',
        ft: '79.9',
        ppg: '8.2',
        rpg: '2.6',
        apg: '1.7',
        bpg: '0.2',
      },
    },
    {
      name: 'Blake Griffin',
      position: 'Forward',
      number: '23',
      height: `6'10"`,
      weight: '250',
      age: 30,
      from: 'Oklahome',
      debut: '2010',
      years: 10,
      stats: {
        mpg: '35',
        fg: '50.2',
        three: '34.2',
        ft: '69.2',
        ppg: '21.9',
        rpg: '9',
        apg: '4.5',
        bpg: '0.5',
      },
    },
    {
      name: 'Reggie Jackson',
      position: 'Guard',
      number: '1',
      height: `6'3"`,
      weight: '208',
      age: 29,
      from: 'Boston College',
      debut: '2011',
      years: 8,
      stats: {
        mpg: '25.2',
        fg: '42.9',
        three: '33.3',
        ft: '85.9',
        ppg: '12.9',
        rpg: '3',
        apg: '4.4',
        bpg: '0.1',
      },
    },
    {
      name: 'Luke Kennard',
      position: 'Guard',
      number: '5',
      height: `6'5"`,
      weight: '206',
      age: 23,
      from: 'Duke',
      debut: '2017',
      years: 2,
      stats: {
        mpg: '21.3',
        fg: '44.1',
        three: '40.3',
        ft: '84.7',
        ppg: '8.6',
        rpg: '2.6',
        apg: '1.8',
        bpg: '0.2',
      },
    },
    {
      name: 'Thon Maker',
      position: 'Forward',
      number: '7',
      height: `7'1"`,
      weight: '221',
      age: 22,
      from: '',
      debut: '2016',
      years: 3,
      stats: {
        mpg: '14.2',
        fg: '42.1',
        three: '32.6',
        ft: '67.7',
        ppg: '4.6',
        rpg: '2.8',
        apg: '0.6',
        bpg: '0.7',
      },
    },
    {
      name: 'Markieff Morris',
      position: 'Forward',
      number: '8',
      height: `6'10"`,
      weight: '245',
      age: 29,
      from: 'Kansas',
      debut: '2011',
      years: 8,
      stats: {
        mpg: '26',
        fg: '44.9',
        three: '33.8',
        ft: '77.8',
        ppg: '11.6',
        rpg: '5.5',
        apg: '1.7',
        bpg: '0.6',
      },
    },
    {
      name: 'Svi Mykhailiuk',
      position: 'Guard',
      number: '19',
      height: `6'8"`,
      weight: '205',
      age: 22,
      from: 'University of Kansas',
      debut: '2018',
      years: 1,
      stats: {
        mpg: '10.5',
        fg: '32.9',
        three: '32.6',
        ft: '60',
        ppg: '3.2',
        rpg: '0.9',
        apg: '0.9',
        bpg: '0',
      },
    },
    {
      name: 'Derrick Rose',
      position: 'Guard',
      number: '25',
      height: `6'3"`,
      weight: '200',
      age: 30,
      from: 'Memphis',
      debut: '2008',
      years: 11,
      stats: {
        mpg: '33.2',
        fg: '45.3',
        three: '30.4',
        ft: '82.4',
        ppg: '18.8',
        rpg: '3.5',
        apg: '5.6',
        bpg: '0.3',
      },
    },
    {
      name: 'Deividas Sirvydis',
      position: 'Guard',
      number: '37',
      height: `6'8"`,
      weight: '190',
      age: 19,
      from: '',
      debut: '',
      years: 0,
      stats: {
        mpg: '0',
        fg: '0',
        three: '0',
        ft: '0',
        ppg: '0',
        rpg: '0',
        apg: '0',
        bpg: '0',
      },
    },
    {
      name: 'Tony Snell',
      position: 'Guard',
      number: '17',
      height: `6'7"`,
      weight: '213',
      age: 27,
      from: '',
      debut: '2013',
      years: 6,
      stats: {
        mpg: '21.8',
        fg: '42.5',
        three: '38.2',
        ft: '81.9',
        ppg: '6.2',
        rpg: '2.4',
        apg: '1',
        bpg: '0.2',
      },
    },
    {
      name: 'Khyri Thomas',
      position: 'Guard',
      number: '13',
      height: `6'3"`,
      weight: '210',
      age: 23,
      from: 'Creighton University',
      debut: '2018',
      years: 1,
      stats: {
        mpg: '7.5',
        fg: '31.9',
        three: '28.6',
        ft: '63.6',
        ppg: '2.3',
        rpg: '0.8',
        apg: '0.3',
        bpg: '0.2',
      },
    },
    {
      name: 'Christian Wood',
      position: 'Forward',
      number: '35',
      height: `6'10"`,
      weight: '214',
      age: 23,
      from: 'UNLV',
      debut: '2015',
      years: 3,
      stats: {
        mpg: '9.8',
        fg: '49.2',
        three: '31',
        ft: '70.7',
        ppg: '5.3',
        rpg: '2.9',
        apg: '0.3',
        bpg: '0.4',
      },
    },
  ],
};

module.exports = roster;
